services:

  mariadb:
    container_name: mariadb
    image: mariadb_image
    build:
      context: ./requirements/mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mariadb_root_pass
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_USER_PASSWORD_FILE=/run/secrets/mariadb_user_pass
      - MARIADB_ADMIN_USER=${MARIADB_ADMIN_USER}
      - MARIADB_ADMIN_PASSWORD_FILE=/run/secrets/mariadb_admin_pass
    secrets:
      - source: mariadb_root_pass
        target: mariadb_root_pass
      - source: mariadb_user_pass
        target: mariadb_user_pass
      - source: mariadb_admin_pass
        target: mariadb_admin_pass
    expose:
      - "3306"
    env_file: .env
    networks:
      - inception

  wordpress:
    container_name: wordpress
    image: wordpress_image
    build:
      context: requirements/wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - MARIADB_USER_PASSWORD_FILE=/run/secrets/mariadb_user_pass
      - WP_DATABASE=${MARIADB_DATABASE}
      - WP_DATABASE_USER=${MARIADB_USER} 
    secrets:
      - source: mariadb_user_pass
        target: mariadb_user_pass
        mode: 0444
      - source: wp_admin_pass
        target: wp_admin_pass
      - source: wp_user_pass
        target: wp_user_pass
    expose:
      - "9000"
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
  
  nginx:
    container_name: nginx
    image: nginx_image
    build:
      context: requirements/nginx
      args:
        - LOGIN
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
      - ../secrets/nginx.crt:/run/secrets/nginx.crt:ro
      - ../secrets/nginx.key:/run/secrets/nginx.key:ro
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - inception

  static:
    container_name: static-site
    build:
      context: ./requirements/static
    image: static_html
    expose:
      - "80"
    networks:
      - inception

  redis:
    image: redis:alpine
    restart: always
    networks:
      - inception
    volumes:
      - redis_data:/data

  ftp:
    container_name: ftp-server
    image: fauria/vsftpd
    restart: always
    ports:
      - "21:21"
      - "20:20"
      - "21100-21110:21100-21110"
    environment:
      - FTP_USER=ftpuser
      - FTP_PASS=ftppass
      - PASV_ADDRESS=127.0.0.1
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
      - LOG_STDOUT=YES
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
    networks:
      - inception

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - "8082:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - inception

volumes:
  mariadb_data:
  wordpress_data:
  redis_data:


secrets:
  mariadb_root_pass:
    file: ../secrets/mariadb_root_pass.txt
  mariadb_admin_pass:
    file: ../secrets/mariadb_admin_pass.txt
  mariadb_user_pass:
    file: ../secrets/mariadb_user_pass.txt
  wp_admin_pass:
    file: ../secrets/wp_admin_pass.txt
  wp_user_pass:
    file: ../secrets/wp_user_pass.txt

networks:
  inception:
    driver: bridge
