services:

  mariadb:
    container_name: mariadb
    image: mariadb_image
    build:
      context: requirements/mariadb
      args:
        - WP_DATABASE
        - WP_USER
        - WP_USER_PASS_FILE
        - WP_ADMIN_USER
        - WP_ADMIN_PASS
        - MARIADB_ROOT_PASSWORD
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - "3306"
    env_file:
      - .env
    networks:
      - inception

  wordpress:
    container_name: wordpress
    image: wordpress_image
    build:
      context: requirements/wordpress
      args:
        - LOGIN
        - DOMAIN
        - WP_TITLE
        - WP_ADMIN_USER
        - WP_ADMIN_PASS
        - WP_ADMIN_EMAIL
        - WP_USER
        - WP_USER_PASS
        - WP_USER_EMAIL
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    expose:
      - "9000"
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception

  nginx:
    container_name: nginx
    image: nginx_image
    build:
      context: requirements/nginx
      args:
        - LOGIN
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
      - ../secrets/nginx.crt:/run/secrets/nginx.crt:ro
      - ../secrets/nginx.key:/run/secrets/nginx.key:ro
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - inception

volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception:
    driver: bridge
