FROM adminer:latest

LABEL maintainer="jolopez- <jolopez-@student.42madrid.com>"

# You can add plugins if needed
# Example:
# RUN curl -L https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1-mysql-en.php -o /var/www/html/plugins/plugin.php

EXPOSE 8080