FROM redis:alpine

LABEL maintainer="jolopez- <jolopez-@student.42madrid.com>"

# Copy custom Redis configuration if needed
# COPY redis.conf /usr/local/etc/redis/redis.conf

# Run Redis
CMD ["redis-server"]